=== *Отчёт по лабораторной работе 3*

Студент: Зернов И.В.

Группа: ПИМ-22

==== 1. Постановка задачи

. ООП. 
    .. Создать интерфейс.
    .. Создать абстрактный класс.
    .. Создать класс, имплементирующий интерфейс.
    .. Создать класс-наследник абстрактного класса.

. Reflection
    .. Выгрузить все поля и методы класса с помощью рефлексии.
    .. Вызвать несколько методов класса.
    .. Вывести на экран всех предков класса.

. Collections
    .. Ознакомится со всеми коллекциями java (list, set, map) и их реализацией.
    .. Продемонстрировать в программе работу с каждым видом реализации коллекции (list, set, map).

. Generics
    .. Сделать дженерик на класс.
    .. Сделать дженерик на метод.

==== 2. Структура проекта

Проект разделён на следующие директории

. *src* - папка, в которой находятся _.java_ файлы
. *out.production.lab3* - папка, в которой находятся _.class_ файлы

==== 3. Информация о реализации

Для выполнения задания использовалась среда разработки IntelliJ IDEA Community Edition 2022.2.3.

==== 4. Выполнение задания

. ООП.
    .. Был создан интерфейс под названием _Human_:
[source,java]
    public interface Human {
        public void showAge(int x);
        public void showRace(String s);
        public void showNation(String n);
    }

    .. Был создан абстрактный класс под названием _Animal_:
[source,java]
public abstract class Animal {
    public abstract void makeSound();
    public abstract void showBreed();
    public void goToSleep(){
        System.out.println("zzzzz");
    }
}

    .. Класс _Student_, имплементирующий интерфейс _Human_:
[source,java]
public class Student implements Human{
    public void showAge(int x) {
        System.out.println(x);
    }
    public void showRace(String s) {
        System.out.println(s);
    }
    public void showNation(String n) {
        System.out.println(n);
    }
    public void showUni(String u){
        System.out.println(u);
    }
    public void showInfo(int x, String s,String n, String u){
        showAge(x);
        showRace(s);
        showNation(n);
        showUni(u);
    }
}

    .. Класс _Dog_ - наследник класса _Animal_:
[source,java]
public class Dog extends Animal{
    public void makeSound(){
        System.out.println("Woof!");
    }
    public void showBreed() {
        System.out.println("Stray Doggo Friend");

    }
}

    .. Класс _Main_ показывающий работу классов, описанных выше
[source,java]
public class Main {
    public static void main(String[] args){
        Student a = new Student();
        a.showInfo(25, "white ","Russian", "RGATU");
        Dog d = new Dog();
        System.out.print("And i have a ");
        d.showBreed();
        d.makeSound();
        d.goToSleep();
    }
}

    .. Результат работы:
[source]
25
white 
Russian
RGATU
And i have a Stray Doggo Friend
Woof!
zzzzz

. Reflection
    .. Был создан класс _TheMirror_, код которого решает поставленные задачи
[source,java]
import java.lang.reflect.*;
public class TheMirror {
    public static void main(String args[])
    {
        System.out.println("----Reflecting Dog Class---");
        System.out.println("----------Methods----------");
        try {
            Class c = Class.forName("Dog");
            Method m[] = c.getDeclaredMethods();
            for (int i = 0; i < m.length; i++)
                System.out.println(m[i].toString());
        }
        catch (Throwable e) {
            System.err.println(e);
        }
        System.out.println("---Invoking class methods--");
        try {
            Class cls = Class.forName("Dog");
            Method meth = cls.getMethod("makeSound");
            Dog sound = new Dog();
            meth.invoke(sound);
            Method meth2 = cls.getMethod("showBreed");
            meth2.invoke(sound);
        }
        catch (Throwable e) {
            System.err.println(e);
        }
        System.out.println("----Show parental class----");
        try {
            Class c2 = Class.forName("Dog");
            System.out.println(c2.getSuperclass());
        }
        catch (Throwable e) {
            System.err.println(e);
        }
    }
}
    .. Результат работы рефлексии
[source,java]
----Reflecting Dog Class---
----------Methods----------
public void Dog.makeSound()
public void Dog.showBreed()
---Invoking class methods--
Woof!
Stray Doggo Friend
----Show parental class----
class Animal

. Collections
    .. Был создан класс _CollectionShowcase_, в котором использованы _map_, _set_ и _list_
[source,java]
import java.util.*;
public class CollectionShowcase {
    public static String getCharForNumber(int i) {//функция чтобы найти букву по номеру
        return i > 0 && i < 27 ? String.valueOf((char)(i + 64)) : null;
    }
    public static void main(String[] args) {
        //------------HashMap------------------------
        HashMap<Integer, String> numAndLetter = new HashMap<>();
        for (int i = 1; i < 27; i++) {
            numAndLetter.put(i, getCharForNumber(i));//заполнение мапы
            //System.out.println(i + " " + getCharForNumber(i));
        }
        HashSet<Integer> numbs = new HashSet<Integer>(numAndLetter.keySet());//создание сета и одновременно выборка данных из мапы
        System.out.println(numbs);
        ArrayList<String> letters = new ArrayList<>(numAndLetter.values());//создание листа и одновременно выборка данных из мапы
        System.out.println(letters);
        System.out.println("Map size - " + numAndLetter.size());//размер мапы
        numAndLetter.clear();//чистка мапы
        System.out.println("Map empty? - "+numAndLetter.isEmpty());//проверка на пустоту мапы
        //--------------Set--------------------------
        for (Integer i = 27; i < 31; i++) {
            numbs.add(i);//добавление чисел к сету
        }
        System.out.println(numbs);
        for (Integer i = 1; i < 26; i++) {
            numbs.remove(i);//удаление из сета
        }
        System.out.println(numbs);
        if (numbs.add(30)){//попытка добавить число, которое уже есть в сете
            System.out.println("Adding that number.");
        }else{
            System.out.println("Can't add that 30. Already in.");
        }
        //---------------ArrayList-------------------
        int lSize = letters.size();//размер листа
        System.out.println("Size of ArrayList - "+lSize);
        for (Integer i=1; i<14; i++){
            letters.remove(getCharForNumber(i));//удаление элементов
            letters.add(getCharForNumber(i));//добавление элементов
        }
        System.out.println(letters);
    }
}
    .. Результат работы программы:
[source,java]
-
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
Map size - 26
Map empty? - true
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
[26, 27, 28, 29, 30]
Can't add that 30. Already in.
Size of ArrayList - 26
[N, O, P, Q, R, S, T, U, V, W, X, Y, Z, A, B, C, D, E, F, G, H, I, J, K, L, M]
-

. Generics
    .. Был создан _generic_ class с названием _GenClass_
[source,java]
public class GenClass <T>{
    private T id;
    GenClass(T id){
        this.id = id;
    }
    public T getId(){
       return id;
    }
}
    .. В следующем классе, _GenMeth_, был сделан _generic_ метод, а также, в нём вызываются методы из _GenClass'a_.
[source,java]
public class GenMeth {
    public static <T> void printT(T[] items){
        for (T item: items){
            System.out.print(item + " ");
        }
    }
    public static void main (String args[]){
        GenClass <String> GC1 = new GenClass<String>("Hello!");
        String a = GC1.getId();
        System.out.println(a);
        GenClass <Integer> GC2 = new GenClass<Integer>(225442);
        Integer b = GC2.getId();
        System.out.println(b);
        GenMeth gm = new GenMeth();
        String[] chars = {"A","B","C"};
        Integer[] numbs = {1,2,3};
        gm.printT(chars);
        gm.printT(numbs);
    }
}
    .. Результат работы:
[source,java]
Hello!
225442
A B C 1 2 3    

==== 6. Вывод
В результате выполнения лабораторной работы были улучшены навыки написания кода на языке Java.
Были изучены интерфейсы и абстрактные классы и успешно использованы на практике.
Были изучены методы _Reflection_, и применены на практике.
Также было произведено знакомство с коллекциями _java_, эти коллекции (map,set,list) были реализованы в коде.
Был создан _generic_ класс и _generic_ метод и протестированы их вызовы.

 
